### PR TITLE
Update arrayTextAdapt.php

### PR DESCRIPTION
**Pull request by BertHankes**
Hi Denis,

It's a PHP >5.5 issue... empty() function on null object
I made a empty wrapper!

My collegae reported a 500 when trying to create a survey.. I will look into that...

### CODE REVIEW

**Comment by Shnoulle** [comment]
You mean when you don't have array question type in survey ?

I have 5.6 : then i can test and fix : i don't like have a wrapper :/

**Comment by Shnoulle** [comment]
Think i use 

```
        $aSettings=$event->get('settings',null,null,array());
        if(!empty($aSettings))
```

Let me check . Maybe only in  2.50 too.

**Comment by Shnoulle** [comment]
I can not reproduce : and really : empty($nullValue) work best

BUT : LS have bug : https://github.com/LimeSurvey/LimeSurvey/commit/7c3efa819cf00ce466f6c66853c9f1200c1635cc

Check if https://github.com/SondagesPro/LS-arrayTextAdapt/commit/db371b242afdbe6acad66052a784a2e4d68c18a3 fix the issue

**Comment by BertHankes** [comment]
I just noticed 500 errror on the forum regarding the plugin. And I experienced it to. So I tried to debug and found the empy() problem. And the wrapper fixed the 500.
The 500 was when you go the the pluginpage as admin.

When making a new survey and 500 is still a problem I need to debug.. Maybe tonight

**Comment by BertHankes** [comment]
plugin surveysModel sufferce the same 500.. I just introduced this plugin and the 500 occured

Fatal error: Can't use method return value in write context in /usr/share/ayh/limesurvey_test/plugins/surveysModel/surveysModel.php on line 93

line 93 having empty(), the problem

BTW running on PHP 7.06 (sorry.. just checked)

**Comment by BertHankes** [comment]
And New Survey also 500
Fatal error: Can't use method return value in write context

**Comment by BertHankes** [comment]
And my is_empy() wrapper is not the solution either...  :-) or :-(

**Comment by BertHankes** [comment]
https://github.com/SondagesPro/LS-arrayTextAdapt/commit/db371b242afdbe6acad66052a784a2e4d68c18a3 works!!!!

**Comment by Shnoulle** [comment]
OK, thanks for empty on surveysModel too :), yes there are some empty() test in it.

But are you sure to have the last version of LimeSUrvey https://github.com/LimeSurvey/LimeSurvey/commit/7c3efa819cf00ce466f6c66853c9f1200c1635cc

**Comment by BertHankes** [comment]
I have 160526 installed

**Comment by Shnoulle** [comment]
See https://github.com/SondagesPro/LS-arrayTextAdapt/pull/2#issuecomment-222201573

**Pull request closed without merging**
